name: Test and deploy

on:
  push:
    branches: 
     - main

jobs:
  test: 
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      -name: Checkout repo
       uses: actions/checkout@v4

      -name: Install dependencies
        run: npm ci

      -name: Setup Postgres
       uses: harmon758/postgresql-action@v1
       with:
         postgresql: nc_news_ci
         postgresql user: test_user
         postgresql password: test_password

      -name: Run tests
        run: PGDATABASE=nc_news_ci PGUSER=test_user PGPASSWORD=test_password npm t
  
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    steps:
      -name: Deploy to Render
        run: curl ${{RENDER_DEPLOY_HOOK_URL}}
